Repository acstech/doppler-events, pull requests merged in 2018-06, with the labels that each got.

#1 Add a description to the README
  README.md
Labels: enhancement

#18 Docker-Compose for Kafka and influx
  .gitignore
  data/influx/.gitkeep
  data/kafka/.gitkeep
  data/zookeeper/.gitkeep
  docker-compose.yml
  tests/connectors_test.sh
  tests/createWorkerKafka.sh
  tests/influxDBAddData.sh
  tests/kafka_test.sh
Labels: Research, enhancement

#19 Peterk/docker ver update
  docker-compose.yml
  tests/createWorkerKafka.sh
  tests/influxDBAddData.sh
Labels: Needs Testing

#29 Peterk/db tags
  docker-compose.yml
  tests/influxDBAddData.sh
  tests/kafka_test.sh
Labels: Needs Testing, enhancement

#38 Producer and Client Working Together
  logs.txt
Labels: Needs Testing, enhancement

#40 Peterk/retention policy
  .gitignore
  README.md
  data/couchbase/.gitkeep
  data/influx_startup/influx_startup.sh
  docker-compose.yml
  tests/connectorsTest.sh
  tests/createWorkerKafka.sh
  tests/influxDBAddData.sh
  tests/kafkaTest.sh
  tests/kafka_test.sh
Labels: enhancement

#47 Peterk/cb config
  .gitignore
  README.md
  cmd/grpcTEST/serviceStart.go
  data/couchbase/.envDefault
  data/influxStartup/influxStartup.sh
  docker-compose.yml
  internal/service/service.go
Labels: Needs Testing, Research, enhancement

#51 Updated README
  README.md
  cmd/testsend/testSend.go
  docker-compose.yml
  tests/influxDBAddData.sh
Labels: enhancement

#54 Update several files
  .gitignore
  README.md
  cmd/testsend/testSend.go
  data/couchbase/.env.default
Labels: enhancement

#56 Peterk/cb update
  cmd/testsend/testSend.go
  internal/service/service.go
Labels: Needs Testing, bug, enhancement

#59 Ben/testing
  cmd/grpcTEST/eventAPIClient/eventAPIClient.go
  cmd/testsend/testSend.go
  data/couchbase/.env.default
  internal/couchbase/couchbaseConn.go
  internal/service/service.go
Labels: Needs Testing, enhancement

#66 Updated error handling in cb connector and server
  cmd/grpcTEST/serviceStart.go
  internal/couchbase/couchbaseConn.go
  internal/service/service.go
Labels: Needs Testing, enhancement

#71 Peterk/error update
  cmd/grpcTEST/serviceStart.go
  cmd/testsend/testSend.go
  internal/couchbase/couchbaseConn.go
  internal/service/service.go
Labels: Needs Testing, enhancement

#74 Peterk/test update
  README.md
  cmd/testsend/testSend.go
  internal/service/service.go
Labels: Needs Testing, enhancement

#77 Peterk/error vague
  data/influx/.gitkeep
  internal/service/service.go
Labels: MVP, enhancement

#78 Error Message Text Update
  internal/couchbase/couchbaseConn.go
  internal/service/service.go
Labels: MVP, enhancement
